using System;
using System.Collections.Generic;
using CESDK.Lua;
using CESDK.Utils;

namespace CESDK.Classes
{
    public class AssemblerException : CesdkException
    {
        public AssemblerException(string message) : base(message) { }
        public AssemblerException(string message, Exception innerException) : base(message, innerException) { }
    }

    public class AutoAssembleResult
    {
        public bool Success { get; init; }
        public Dictionary<string, object?>? DisableInfo { get; init; }
        public List<string>? Warnings { get; init; }
    }

    public static class Assembler
    {
        private static readonly LuaNative lua = PluginContext.Lua;

        /// <summary>
        /// Assembles a single line of code and returns the generated bytes.
        /// </summary>
        /// <param name="line">Instruction to assemble (e.g. "nop", "mov eax,ebx")</param>
        /// <param name="address">Address to assemble at (affects relative addresses)</param>
        /// <param name="assemblePreference">0=apNone, 1=apShort, 2=apLong, 3=apFar</param>
        /// <returns>Byte array of assembled instruction</returns>
        public static byte[] Assemble(string line, ulong address = 0, int assemblePreference = 0) =>
            WrapException(() => LuaUtils.CallLuaFunction("assemble", $"assemble '{line}'",
                LuaUtils.ExtractBytesFromTable, line, address, assemblePreference));

        /// <summary>
        /// Runs the auto assembler with the given script text.
        /// </summary>
        /// <param name="script">Auto assembler script with [ENABLE]/[DISABLE] sections</param>
        /// <param name="targetSelf">If true, assemble into CE process instead of target</param>
        /// <returns>True on success</returns>
        public static bool AutoAssemble(string script, bool targetSelf = false)
        {
            return WrapException(() =>
            {
                lua.GetGlobal("autoAssemble");
                if (!lua.IsFunction(-1))
                {
                    lua.Pop(1);
                    throw new InvalidOperationException("autoAssemble function not available in this CE version");
                }

                lua.PushString(script);
                if (targetSelf)
                    lua.PushBoolean(true);

                int nargs = targetSelf ? 2 : 1;
                var result = lua.PCall(nargs, 1);
                if (result != 0)
                {
                    var error = lua.ToString(-1);
                    lua.Pop(1);
                    throw new InvalidOperationException($"autoAssemble() call failed: {error}");
                }

                var success = lua.ToBoolean(-1);
                lua.Pop(1);
                return success;
            });
        }

        /// <summary>
        /// Checks an auto assembler script for syntax errors without executing it.
        /// </summary>
        /// <param name="script">Auto assembler script</param>
        /// <param name="enable">Check in enable or disable mode</param>
        /// <param name="targetSelf">If true, check against CE process</param>
        /// <returns>Tuple of (success, errorMessage). errorMessage is null on success.</returns>
        public static (bool success, string? errorMessage) AutoAssembleCheck(string script, bool enable = true, bool targetSelf = false)
        {
            return WrapException(() =>
            {
                lua.GetGlobal("autoAssembleCheck");
                if (!lua.IsFunction(-1))
                {
                    lua.Pop(1);
                    throw new InvalidOperationException("autoAssembleCheck function not available in this CE version");
                }

                lua.PushString(script);
                lua.PushBoolean(enable);
                lua.PushBoolean(targetSelf);

                var result = lua.PCall(3, 2);
                if (result != 0)
                {
                    var error = lua.ToString(-1);
                    lua.Pop(1);
                    throw new InvalidOperationException($"autoAssembleCheck() call failed: {error}");
                }

                var success = lua.ToBoolean(-2);
                string? errorMessage = null;
                if (!success && lua.IsString(-1))
                    errorMessage = lua.ToString(-1);

                lua.Pop(2);
                return (success, errorMessage);
            });
        }

        /// <summary>
        /// Sets the assembler mode for assembly operations.
        /// </summary>
        /// <param name="is64Bit">True for 64-bit mode, false for 32-bit</param>
        public static void SetAssemblerMode(bool is64Bit) =>
            WrapException(() => LuaUtils.CallVoidLuaFunction("setAssemblerMode", "set assembler mode", is64Bit ? 1 : 0));

        private static T WrapException<T>(Func<T> operation)
        {
            try { return operation(); }
            catch (InvalidOperationException ex) { throw new AssemblerException(ex.Message, ex); }
        }

        private static void WrapException(Action operation)
        {
            try { operation(); }
            catch (InvalidOperationException ex) { throw new AssemblerException(ex.Message, ex); }
        }
    }
}
