using System;
using System.Collections.Generic;
using CESDK.Lua;
using CESDK.Utils;

namespace CESDK.Classes
{
    public class AssemblerException : CesdkException
    {
        public AssemblerException(string message) : base(message) { }
        public AssemblerException(string message, Exception innerException) : base(message, innerException) { }
    }

    public sealed class AutoAssembleResult
    {
        public string DisableId { get; init; } = string.Empty;
        public List<string> Warnings { get; init; } = [];
    }

    public static class Assembler
    {
        private static readonly LuaNative lua = PluginContext.Lua;
        private const string SessionTableName = "__ce_mcp_auto_assemble_sessions";


        /// <summary>
        /// Assembles a single line of code and returns the generated bytes.
        /// </summary>
        /// <param name="line">Instruction to assemble (e.g. "nop", "mov eax,ebx")</param>
        /// <param name="address">Address to assemble at (affects relative addresses)</param>
        /// <param name="assemblePreference">0=apNone, 1=apShort, 2=apLong, 3=apFar</param>
        /// <returns>Byte array of assembled instruction</returns>
        public static byte[] Assemble(
            string line,
            ulong address = 0,
            int assemblePreference = 0,
            bool skipRangeCheck = false) =>
            WrapException(() => LuaUtils.CallLuaFunction("assemble", $"assemble '{line}'",
                LuaUtils.ExtractBytesFromTable, line, address, assemblePreference, skipRangeCheck));

        /// <summary>
        /// Runs the auto assembler with the given script text.
        /// </summary>
        /// <param name="script">Auto assembler script with [ENABLE]/[DISABLE] sections</param>
        /// <param name="targetSelf">If true, assemble into CE process instead of target</param>
        /// <returns>True on success</returns>
        public static AutoAssembleResult AutoAssemble(string script, bool targetSelf = false)
        {
            return WrapException(() =>
            {
                int initialTop = lua.GetTop();
                try
                {
                    lua.GetGlobal("autoAssemble");
                    if (!lua.IsFunction(-1))
                        throw new InvalidOperationException("autoAssemble function not available");

                    lua.PushString(script);
                    lua.PushBoolean(targetSelf);
                    int callResult = lua.PCall(2, 3);
                    if (callResult != 0)
                        throw new InvalidOperationException($"autoAssemble() call failed: {lua.ToString(-1)}");
                    if (!lua.ToBoolean(-3))
                        throw new InvalidOperationException(lua.ToString(-2) ?? "Auto Assembler rejected the script");
                    if (!lua.IsTable(-2))
                        throw new InvalidOperationException("autoAssemble did not return disable information");

                    string disableId = Guid.NewGuid().ToString("N");
                    int disableInfoIndex = initialTop + 2;
                    List<string> warnings = ReadStringList(-1);

                    int sessionsIndex = GetOrCreateSessionTable();
                    lua.CreateTable();
                    lua.PushValue(disableInfoIndex);
                    lua.SetField(-2, "disableInfo");
                    lua.PushBoolean(targetSelf);
                    lua.SetField(-2, "targetSelf");
                    lua.SetField(sessionsIndex, disableId);

                    return new AutoAssembleResult
                    {
                        DisableId = disableId,
                        Warnings = warnings
                    };
                }
                finally
                {
                    lua.SetTop(initialTop);
                }
            });
        }

        /// <summary>
        /// Executes a script's disable section using state returned by the matching enable call.
        /// </summary>
        public static void AutoAssembleDisable(string script, string disableId)
        {
            WrapException(() =>
            {
                int initialTop = lua.GetTop();
                try
                {
                    int sessionsIndex = GetSessionTable();
                    lua.GetField(sessionsIndex, disableId);
                    if (!lua.IsTable(-1))
                        throw new InvalidOperationException($"Unknown Auto Assembler disable ID '{disableId}'");
                    int sessionIndex = lua.GetTop();

                    lua.GetField(sessionIndex, "targetSelf");
                    bool targetSelf = lua.ToBoolean(-1);
                    lua.Pop(1);

                    lua.GetGlobal("autoAssemble");
                    if (!lua.IsFunction(-1))
                        throw new InvalidOperationException("autoAssemble function not available");
                    lua.PushString(script);
                    lua.PushBoolean(targetSelf);
                    lua.GetField(sessionIndex, "disableInfo");

                    int callResult = lua.PCall(3, 1);
                    if (callResult != 0)
                        throw new InvalidOperationException($"autoAssemble() disable call failed: {lua.ToString(-1)}");
                    if (!lua.ToBoolean(-1))
                        throw new InvalidOperationException("Auto Assembler rejected the disable section");

                    lua.PushNil();
                    lua.SetField(sessionsIndex, disableId);
                }
                finally
                {
                    lua.SetTop(initialTop);
                }
            });
        }

        /// <summary>
        /// Checks an auto assembler script for syntax errors without executing it.
        /// </summary>
        /// <param name="script">Auto assembler script</param>
        /// <param name="enable">Check in enable or disable mode</param>
        /// <param name="targetSelf">If true, check against CE process</param>
        /// <returns>Tuple of (success, errorMessage). errorMessage is null on success.</returns>
        public static (bool success, string? errorMessage) AutoAssembleCheck(string script, bool enable = true, bool targetSelf = false)
        {
            return WrapException(() =>
            {
                int initialTop = lua.GetTop();
                try
                {
                    lua.GetGlobal("autoAssembleCheck");
                    if (!lua.IsFunction(-1))
                        throw new InvalidOperationException("autoAssembleCheck function not available");

                    lua.PushString(script);
                    lua.PushBoolean(enable);
                    lua.PushBoolean(targetSelf);
                    int result = lua.PCall(3, 2);
                    if (result != 0)
                        throw new InvalidOperationException($"autoAssembleCheck() call failed: {lua.ToString(-1)}");

                    bool success = lua.ToBoolean(-2);
                    string? errorMessage = !success && lua.IsString(-1) ? lua.ToString(-1) : null;
                    return (success, errorMessage);
                }
                finally
                {
                    lua.SetTop(initialTop);
                }
            });
        }

        /// <summary>
        /// Sets the assembler mode for assembly operations.
        /// </summary>
        /// <param name="is64Bit">True for 64-bit mode, false for 32-bit</param>
        public static void SetAssemblerMode(bool is64Bit) =>
            WrapException(() => LuaUtils.CallVoidLuaFunction("setAssemblerMode", "set assembler mode", is64Bit ? 1 : 0));

        private static int GetOrCreateSessionTable()
        {
            lua.GetGlobal(SessionTableName);
            if (lua.IsTable(-1))
                return lua.GetTop();

            lua.Pop(1);
            lua.CreateTable();
            lua.PushValue(-1);
            lua.SetGlobal(SessionTableName);
            return lua.GetTop();
        }

        private static int GetSessionTable()
        {
            lua.GetGlobal(SessionTableName);
            if (!lua.IsTable(-1))
                throw new InvalidOperationException("No Auto Assembler disable sessions are active");
            return lua.GetTop();
        }

        private static List<string> ReadStringList(int index)
        {
            if (lua.IsNil(index))
                return [];
            if (!lua.IsTable(index))
                throw new InvalidOperationException("Auto Assembler returned invalid warnings");

            int absoluteIndex = index < 0 ? lua.GetTop() + index + 1 : index;
            int count = lua.RawLen(absoluteIndex);
            var values = new List<string>(count);
            for (int itemIndex = 1; itemIndex <= count; itemIndex++)
            {
                lua.PushInteger(itemIndex);
                lua.GetTable(absoluteIndex);
                try
                {
                    values.Add(lua.ToString(-1) ?? "");
                }
                finally
                {
                    lua.Pop(1);
                }
            }
            return values;
        }

        private static T WrapException<T>(Func<T> operation)
        {
            try { return operation(); }
            catch (InvalidOperationException ex) { throw new AssemblerException(ex.Message, ex); }
        }

        private static void WrapException(Action operation)
        {
            try { operation(); }
            catch (InvalidOperationException ex) { throw new AssemblerException(ex.Message, ex); }
        }
    }
}
